STANDARD_FEATURE_VALUES = {
    "flooring": [
        "hardwood",
        "engineered hardwood",
        "bamboo",
        "laminate",
        "tile",
        "stone",
        "terrazzo",
        "vinyl",
        "linoleum",
        "cork",
        "concrete",
        "epoxy",
        "carpet",
        "unfinished",
        "other",
    ],
    "wall_finish": [
        "painted",
        "wallpaper",
        "tile",
        "wood paneling",
        "shiplap",
        "wainscoting",
        "plaster",
        "stone veneer",
        "exposed brick",
        "unfinished",
        "other",
    ],
    "ceiling": [
        "flat",
        "tray",
        "cove",
        "vaulted",
        "beamed",
        "coffered",
        "tin",
        "wood plank",
        "drop ceiling",
        "popcorn",
        "exposed",
        "unfinished",
        "other",
    ],
    "lighting_fixtures": [
        "recessed",
        "track",
        "pendant",
        "chandelier",
        "flush mount",
        "ceiling fan light",
        "under-cabinet",
        "wall sconces",
        "vanity lights",
        "none",
        "other",
    ],
    "trim_baseboards": [
        "white painted",
        "stained wood",
        "modern flush",
        "ornate/detailed",
        "crown molding",
        "none",
        "other",
    ],
    "windows": [
        "single-hung",
        "double-hung",
        "casement",
        "awning",
        "sliding",
        "picture",
        "bay/bow",
        "garden",
        "arched",
        "clerestory",
        "skylight",
        "impact",
        "none",
        "other",
    ],
    "window_treatments": [
        "blinds",
        "plantation shutters",
        "curtains/drapes",
        "sheer curtains",
        "blackout curtains",
        "roman shades",
        "roller shades",
        "valances",
        "frosted glass",
        "none",
        "other",
    ],
    "doors": [
        "wood panel",
        "flush",
        "french",
        "sliding",
        "barn",
        "pocket",
        "bifold",
        "louvered",
        "arched",
        "glass",
        "impact",
        "none",
        "other",
    ],
    "built_ins": [
        "bookshelves",
        "cabinets",
        "media console",
        "closet organizers",
        "desk",
        "storage bench",
        "window seat",
        "mudroom cubbies",
        "wine rack",
        "fireplace surround",
        "none",
        "other",
    ],
    "hvac_vents": [
        "floor vent",
        "wall vent",
        "ceiling vent",
        "radiator",
        "baseboard heater",
        "radiant floor",
        "mini split (wall cassette)",
        "ceiling cassette",
        "window unit",
        "none",
        "other",
    ],
    "electrical_outlets": [
        "standard",
        "usb integrated",
        "smart",
        "floor outlet",
        "GFCI",
        "none",
        "other",
    ],
    "countertops": [
        "granite",
        "quartz",
        "marble",
        "butcher block",
        "concrete",
        "solid surface",
        "laminate",
        "tile",
        "stainless steel",
        "none",
        "other",
    ],
    "cabinet_style": [
        "shaker",
        "raised panel",
        "flat panel",
        "glass-front",
        "open shelving",
        "beadboard",
        "louvered",
        "wood"
        "none",
        "other",
    ],
    "backsplash": [
        "subway tile",
        "mosaic",
        "glass",
        "stone",
        "metal",
        "brick",
        "none",
        "other",
    ],
    "fireplace": [
        "wood-burning",
        "gas",
        "electric",
        "decorative/non-functional",
        "none",
        "other",
    ],
    "staircase": [
        "straight",
        "L-shaped",
        "U-shaped",
        "spiral",
        "floating",
        "split",
        "none",
        "other",
    ],
    "plumbing_fixtures_finish": [
        "chrome",
        "brushed nickel",
        "matte black",
        "oil-rubbed bronze",
        "polished brass",
        "stainless steel",
        "other",
    ],
    "hardware_finish": [
        "chrome",
        "brushed nickel",
        "black",
        "brass",
        "bronze",
        "mixed",
        "other",
    ],
    "appliances_color": [
        "stainless steel",
        "black",
        "white",
        "panel-ready",
        "black stainless",
        "other",
    ],
    "misc": [
        "smart thermostat",
        "smart lighting",
        "smart lock",
        "video doorbell",
        "security camera",
        "smoke alarm",
        "none",
        "other",
    ],
} 